name: "release"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: create release
        uses: ntltd/release-generator@master
        with:
          baseTag: ${{ github.event.release.tag_name }}
          releaseTag: ${{ github.event.release.tag_name }}
          prerelease: false
          draft: false
          releaseName: ${{ github.event.release.tag_name }}
          templatePath: templates/release.md
          token: ${{ github.token }}
