name: "main"

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/main.yaml"
      - ".github/template*"
      - "package.json"
      - "src/**"
      - "tests/*"
      - "tsconfig.json"
      - "tslint.json"
  pull_request:
    paths:
      - ".github/workflows/main.yaml"
      - ".github/template*"
      - "package.json"
      - "src/**"
      - "tests/*"
      - "tsconfig.json"
      - "tslint.json"

jobs:
  unit_test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v1.2.0
      - name: Lint code
        run: yarn lint
      - name: Test code
        run: yarn test
  integration_test:
    if: github.ref == 'refs/heads/master'
    name: integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v1.2.0
      - name: Create Release
        uses: minddocdev/mou-release-action@master
        with:
          baseTag: ${{ github.event.release.tag_name }}
          prerelease: false
          draft: false
          releaseName: ${{ github.event.release.tag_name }}
          templatePath: templates/release.md
          token: ${{ github.token }}
