name: "release"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  integration:
    if: github.ref == 'refs/heads/master'
    name: integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Create Release
        uses: ntltd/release-generator@master
        with:
          baseTag: ${{ github.event.release.tag_name }}
          releaseTag: ${{ github.event.release.tag_name }}
          prerelease: false
          draft: false
          releaseName: ${{ github.event.release.tag_name }}
          templatePath: templates/release.md
          token: ${{ github.token }}
