name: "test"

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows*"
      - ".github/template*"
      - "package.json"
      - "src/**"
      - "tests/*"
      - "tsconfig.json"
      - "tslint.json"
  pull_request:
    paths:
      - ".github/workflows*"
      - ".github/template*"
      - "package.json"
      - "src/**"
      - "tests/*"
      - "tsconfig.json"
      - "tslint.json"

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: linter
        run: yarn lint
      - name: jest
        run: yarn test
