name: "test"

on:
  push:
    branches:
      - "master"

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: linter
        run: yarn lint
      - name: jest
        run: yarn test
